import { useGoogleAuth } from '@/common/hooks/useGoogleAuth'
import { PublicPage } from '@/components/pagesComponents/publicPage/PublicPage'
import { getBaseLayout } from '@/components/ui/layout'
import { publicUserService } from '@/services/publicUser'
import { GetStaticProps } from 'next'
import Head from 'next/head'

import { NextPageWithLayout } from './_app'

type Props = {
  totalCount: number
}

export const getStaticProps: GetStaticProps = async () => {
  const { totalCount } = await publicUserService.getTotalUsers()

  return {
    props: {
      totalCount,
    },
    revalidate: 60,
  }
}

const Home: NextPageWithLayout<Props> = ({ totalCount }) => {
  const { isLoading } = useGoogleAuth()

  if (isLoading) {
    return <div>LOADING ...</div>
  }

  return (
    <>
      <Head>
        <title>Inctagram</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <>
        <PublicPage totalUsers={totalCount} />
      </>
    </>
  )
}

Home.getLayout = getBaseLayout
export default Home
