import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Inctagram</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <div>
        <h1>Samuraichiki team</h1>
      </div>
    </>
  )
}
